# Generated by Django 5.1.5 on 2025-01-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subject1', models.DecimalField(decimal_places=2, max_digits=5)),
                ('subject2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('subject3', models.DecimalField(decimal_places=2, max_digits=5)),
                ('subject4', models.DecimalField(decimal_places=2, max_digits=5)),
                ('subject5', models.DecimalField(decimal_places=2, max_digits=5)),
                ('subject6', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
